/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.1/userguide/building_java_projects.html in the Gradle documentation.
 */

import com.android.build.api.dsl.LibraryExtension
import org.gradle.api.tasks.testing.logging.TestExceptionFormat
import org.gradle.api.tasks.testing.logging.TestLogEvent
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.android.kotlin.multiplatform.library)
    alias(libs.plugins.vanniktech.mavenPublish)
}

val groupId = "io.github.initdc"
val artifactId = "types"
val version = "0.0.1"

kotlin {
    jvm {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_11)
        }
    }

    // Tier 1
    macosArm64()
    iosSimulatorArm64()
    iosArm64()

    // Tier 2
    linuxX64()
    linuxArm64()

    // Tier 3
    mingwX64()
    macosX64()
    iosX64()

    androidLibrary {
        androidResources {
            enable = false
        }

        namespace = groupId
        compileSdk = 36
        minSdk = 24

        withJava()
        withHostTestBuilder {}.configure {}
        withDeviceTestBuilder {
            sourceSetTreeName = "test"
        }

        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_11)
        }
    }

    sourceSets {
        val commonMain by getting {
            kotlin.srcDir("src/main/kotlin")
            dependencies {}
        }

        val commonTest by getting {
            kotlin.srcDir("src/test/kotlin")
            dependencies {
                implementation(libs.kotlin.test)
            }
        }

        val jvmTest by getting {
            dependencies {
                implementation(libs.junit.jupiter.engine)
            }
        }
    }
}

tasks.withType<Test> {
    testLogging {
        showExceptions = true
        showStandardStreams = true
        events = setOf(TestLogEvent.PASSED, TestLogEvent.FAILED, TestLogEvent.SKIPPED)
        exceptionFormat = TestExceptionFormat.FULL
    }
}

val user = "initdc"
val repo = "kt.types"
val github = "github.com/$user/$repo"

mavenPublishing {
    publishToMavenCentral()
    signAllPublications()
    coordinates(groupId, artifactId, version)

    pom {
        name = repo
        description = "Bring the Rust [Result Option] types to Kotlin"
        url = "https://$github"

        licenses {
            license {
                name = "Mozilla Public License 2.0"
                url = "https://www.mozilla.org/MPL/2.0/"
            }
        }
        developers {
            developer {
                id = user
                name = user
                email = "initd@outlook.com"
            }
        }
        scm {
            connection = "scm:git:git://$github.git"
            developerConnection = "scm:git:ssh://$github.git"
            url = "https://$github"
        }
    }
}

publishing {
    repositories {
        maven {
            name = "github"
            url = uri("https://maven.pkg.github.com/$user/$repo")
            credentials {
                username = project.findProperty("gpr.user") as String? ?: System.getenv("GHPUSER")
                password = project.findProperty("gpr.key") as String? ?: System.getenv("GHPKEY")
            }
        }
    }

    // publications {
    //     register<MavenPublication>("lib") {
    //         groupId = "kt.lib"
    //         from(components["kotlin"])
    //     }
    // }
}
